export const SET_SIZE = "SET_SIZE";
export const INIT_TILES = "INIT_TILES";
export const SET_FIELD = "SET_FIELD";
export const CLEAR_FIELD = "CLEAR_FIELD";
export const UPDATE_TILE = "SET_TILE";

export const UPDATE_TURN_COUNTER = "UPDATE_TURN_COUNTER";
export const RESET_TURN_COUNTER = "RESET_TURN_COUNTER";

export const UPDATE_GAME_SCORE = "UPDATE_GAME_SCORE";
export const RESET_GAME_SCORE = "RESET_GAME_SCORE";
